/**
 * Manifest stiker: emoji -> nama file di public/stickers/.
 *
 * DILABELI MANUAL (bukan model API) dengan membaca TEKS di setiap stiker lebih
 * dulu, baru konsep gambarnya. Alasan: pelabelan otomatis hanya melihat ekspresi
 * wajah sehingga sering salah — contoh nyata: stk_007 (orang dimarahi atasan)
 * dilabeli tawa, padahal maknanya kena tegur/tegang.
 *
 * Sumber kebenaran: scripts/build_sticker_manifest.py (nomor -> emoji/teks/konteks).
 * Jalankan ulang setelah mengubah label:
 *   python scripts/build_sticker_manifest.py
 */
export const STICKER_MANIFEST: Record<string, string> = {
  "✋": "stk_093.webp",
  "❄️": "stk_072.webp",
  "⬜": "stk_051.webp",
  "⭐": "stk_027.webp",
  "🆗": "stk_015.webp",
  "🍜": "stk_026.webp",
  "🍳": "stk_094.webp",
  "🎂": "stk_188.webp",
  "🎓": "stk_084.webp",
  "🎮": "stk_022.webp",
  "🏃": "stk_042.webp",
  "🏍️": "stk_198.webp",
  "🐌": "stk_112.webp",
  "🐟": "stk_110.webp",
  "🐱": "stk_044.webp",
  "🐶": "stk_055.webp",
  "🐷": "stk_009.webp",
  "👀": "stk_114.webp",
  "👌": "stk_016.webp",
  "👍": "stk_025.webp",
  "👎": "stk_030.webp",
  "👑": "stk_156.webp",
  "👶": "stk_139.webp",
  "💀": "stk_220.webp",
  "💁": "stk_148.webp",
  "💔": "stk_116.webp",
  "💡": "stk_066.webp",
  "💥": "stk_168.webp",
  "💩": "stk_201.webp",
  "💪": "stk_078.webp",
  "💸": "stk_134.webp",
  "📄": "stk_144.webp",
  "📍": "stk_087.webp",
  "📝": "stk_124.webp",
  "📞": "stk_209.webp",
  "📱": "stk_111.webp",
  "🔍": "stk_120.webp",
  "🔔": "stk_023.webp",
  "🕴️": "stk_174.webp",
  "🖐️": "stk_107.webp",
  "🖕": "stk_006.webp",
  "🗣️": "stk_142.webp",
  "😁": "stk_063.webp",
  "😂": "stk_013.webp",
  "😅": "stk_173.webp",
  "😈": "stk_008.webp",
  "😊": "stk_164.webp",
  "😍": "stk_159.webp",
  "😎": "stk_019.webp",
  "😏": "stk_018.webp",
  "😐": "stk_097.webp",
  "😒": "stk_010.webp",
  "😔": "stk_003.webp",
  "😛": "stk_200.webp",
  "😜": "stk_005.webp",
  "😡": "stk_075.webp",
  "😢": "stk_145.webp",
  "😤": "stk_076.webp",
  "😧": "stk_068.webp",
  "😩": "stk_011.webp",
  "😫": "stk_069.webp",
  "😬": "stk_007.webp",
  "😭": "stk_017.webp",
  "😮": "stk_054.webp",
  "😯": "stk_123.webp",
  "😰": "stk_195.webp",
  "😱": "stk_088.webp",
  "😲": "stk_147.webp",
  "😳": "stk_137.webp",
  "😴": "stk_049.webp",
  "😵": "stk_176.webp",
  "😹": "stk_180.webp",
  "😺": "stk_191.webp",
  "😼": "stk_095.webp",
  "😾": "stk_037.webp",
  "😿": "stk_012.webp",
  "🙂": "stk_048.webp",
  "🙄": "stk_028.webp",
  "🙅": "stk_046.webp",
  "🙈": "stk_038.webp",
  "🙉": "stk_040.webp",
  "🙏": "stk_041.webp",
  "🚀": "stk_091.webp",
  "🚗": "stk_045.webp",
  "🚫": "stk_053.webp",
  "🚶": "stk_033.webp",
  "🚿": "stk_119.webp",
  "🛁": "stk_141.webp",
  "🛌": "stk_181.webp",
  "🤔": "stk_131.webp",
  "🤝": "stk_050.webp",
  "🤠": "stk_105.webp",
  "🤣": "stk_202.webp",
  "🤥": "stk_032.webp",
  "🤦": "stk_155.webp",
  "🤨": "stk_031.webp",
  "🤪": "stk_024.webp",
  "🤫": "stk_001.webp",
  "🤬": "stk_117.webp",
  "🤭": "stk_039.webp",
  "🤯": "stk_004.webp",
  "🤲": "stk_207.webp",
  "🤷": "stk_059.webp",
  "🥱": "stk_082.webp",
  "🥺": "stk_002.webp",
  "🧒": "stk_101.webp",
  "🧘": "stk_021.webp",
  "🧠": "stk_014.webp",
  "🧼": "stk_157.webp",
  "🫡": "stk_099.webp",
};

/**
 * Emoji "keras" (umpatan/provokasi). Boleh dipakai bot HANYA saat konteks bercanda
 * (user bercanda/roasting/mengirim stiker serupa lebih dulu) — lihat guard di runtime.
 */
export const EDGY_STICKER_EMOJIS: string[] = [
  "🖕",
  "😈",
  "🤬",
  "💩",
  "💀",
];
