/**
 * Manifest stiker: emoji -> nama file di public/stickers/.
 * Digenerate otomatis dari pelabelan vision (scripts/label_stickers.py).
 * JANGAN edit manual — jalankan ulang generator bila aset berubah:
 *   python scripts/label_stickers.py && python scripts/gen_sticker_manifest.py
 */
export const STICKER_MANIFEST: Record<string, string> = {
  "✋": "stk_093.webp",
  "🎉": "stk_188.webp",
  "🏃": "stk_127.webp",
  "🐱": "stk_044.webp",
  "👀": "stk_023.webp",
  "👊": "stk_129.webp",
  "👋": "stk_041.webp",
  "👍": "stk_050.webp",
  "👎": "stk_030.webp",
  "💔": "stk_145.webp",
  "💪": "stk_133.webp",
  "📉": "stk_092.webp",
  "📍": "stk_087.webp",
  "📝": "stk_124.webp",
  "📞": "stk_209.webp",
  "📢": "stk_022.webp",
  "📸": "stk_101.webp",
  "🖕": "stk_006.webp",
  "😂": "stk_007.webp",
  "😃": "stk_036.webp",
  "😄": "stk_111.webp",
  "😅": "stk_064.webp",
  "😆": "stk_008.webp",
  "😈": "stk_143.webp",
  "😌": "stk_079.webp",
  "😎": "stk_091.webp",
  "😏": "stk_003.webp",
  "😐": "stk_162.webp",
  "😑": "stk_051.webp",
  "😒": "stk_028.webp",
  "😔": "stk_017.webp",
  "😗": "stk_187.webp",
  "😘": "stk_089.webp",
  "😜": "stk_146.webp",
  "😠": "stk_075.webp",
  "😢": "stk_060.webp",
  "😧": "stk_123.webp",
  "😨": "stk_100.webp",
  "😩": "stk_061.webp",
  "😪": "stk_070.webp",
  "😭": "stk_029.webp",
  "😮": "stk_021.webp",
  "😮‍💨": "stk_181.webp",
  "😰": "stk_173.webp",
  "😱": "stk_004.webp",
  "😲": "stk_054.webp",
  "😳": "stk_002.webp",
  "😴": "stk_011.webp",
  "😵": "stk_015.webp",
  "😸": "stk_171.webp",
  "😼": "stk_218.webp",
  "😾": "stk_167.webp",
  "😿": "stk_005.webp",
  "🙀": "stk_103.webp",
  "🙃": "stk_164.webp",
  "🙄": "stk_010.webp",
  "🙅": "stk_046.webp",
  "🙊": "stk_001.webp",
  "🙏": "stk_059.webp",
  "🚀": "stk_086.webp",
  "🚶": "stk_045.webp",
  "🤐": "stk_109.webp",
  "🤔": "stk_065.webp",
  "🤗": "stk_137.webp",
  "🤝": "stk_052.webp",
  "🤢": "stk_032.webp",
  "🤣": "stk_166.webp",
  "🤦": "stk_031.webp",
  "🤨": "stk_025.webp",
  "🤩": "stk_024.webp",
  "🤪": "stk_219.webp",
  "🤫": "stk_016.webp",
  "🤬": "stk_009.webp",
  "🤭": "stk_216.webp",
  "🤯": "stk_035.webp",
  "🤲": "stk_207.webp",
  "🤷": "stk_107.webp",
  "🥰": "stk_055.webp",
  "🥱": "stk_182.webp",
  "🥺": "stk_012.webp",
  "🧐": "stk_019.webp",
  "🧘": "stk_151.webp",
  "🧠": "stk_014.webp",
  "🧼": "stk_119.webp",
  "🫠": "stk_221.webp",
  "🫣": "stk_175.webp",
};

/**
 * Emoji "keras" (umpatan/provokasi). Boleh dipakai bot HANYA saat konteks bercanda
 * (user bercanda/roasting/mengirim stiker serupa lebih dulu) — lihat guard di runtime.
 */
export const EDGY_STICKER_EMOJIS: string[] = [
  "👊",
  "🖕",
  "😈",
  "😠",
  "🤬",
];
